services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-optima
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: licensing-service
    volumes:
      - ../databases/mongodb-licensing-service:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  config-server:
    container_name: config-server
    build:
      context: .\cloud\config-server
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/config-server-0.0.1-SNAPSHOT.jar
    ports:
      - 8071:8071
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
      SPRING_PROFILES_ACTIVE: native


  licensing-service:
    container_name: licensing-service
    build:
      context: .\services\License Service
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/licensing-service-0.0.1-SNAPSHOT.jar
    ports:
      - 8081:8081
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:password@mongodb:27017/licensing-service?authSource=admin
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://admin:admin-password@config-server:8071
    depends_on:
      config-server:
        condition: service_started
      mongodb:
        condition: service_healthy