spring:
  mvc:
    problemdetails:
      enabled: true

  application:
    name: Licensing-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:password@localhost:27017/licensing-service?authSource=admin}
#      host: localhost
#      database: licensing-service
#      port: 27017
#      username: root
#      password: password
#      authentication-database: admin

management:
  health:
    diskspace:
      enabled: true
  endpoint:
    health:
      show-details: always
      access: read_only
  endpoints:
    web:
      exposure:
#        include: health, info, metrics, prometheus
        include: "*"
      discovery:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      application: Licensing-service

server:
  port: 8081
